export const HEADMASTER = "HEADMASTER";
export const ACADEMIC_MASTER = "ACADEMIC_MASTER";
export const TEACHER = "TEACHER";
export const ACCOUNTANT = "ACCOUNTANT";
export const PARENT = "PARENT";
export const STUDENT = "STUDENT";
export const SUPER_ADMIN = "SUPER_ADMIN";

export const PEOPLE_MANAGE = [HEADMASTER, ACADEMIC_MASTER];
export const ACADEMIC_STAFF = [HEADMASTER, ACADEMIC_MASTER, TEACHER];
export const STUDENT_DIRECTORY = [HEADMASTER, ACADEMIC_MASTER, TEACHER, ACCOUNTANT];
export const TEACHER_MANAGE = [HEADMASTER, ACADEMIC_MASTER];
export const TIMETABLE = [HEADMASTER, ACADEMIC_MASTER, TEACHER];
export const EXAMS = [HEADMASTER, ACADEMIC_MASTER, TEACHER];
export const FINANCE = [HEADMASTER, ACADEMIC_MASTER, ACCOUNTANT, PARENT];
export const FINANCE_MANAGE = [ACCOUNTANT];
export const MESSAGES = [HEADMASTER, ACADEMIC_MASTER, TEACHER, ACCOUNTANT, PARENT];
export const NOTICES = [HEADMASTER, ACADEMIC_MASTER, TEACHER, ACCOUNTANT, STUDENT, PARENT];
export const AUDIT = [HEADMASTER, ACADEMIC_MASTER, ACCOUNTANT];
export const DASHBOARD = [HEADMASTER, ACADEMIC_MASTER, ACCOUNTANT];
export const SCHOOL_OFFICERS = [HEADMASTER, ACADEMIC_MASTER, ACCOUNTANT];
export const ORG_SCHOOLS = [SUPER_ADMIN, HEADMASTER];

export function hasRole(role, roles) {
  return Boolean(role && roles.includes(role));
}

export const ROLE_LABELS = {
  SUPER_ADMIN: "Platform admin",
  HEADMASTER: "Headmaster",
  ACADEMIC_MASTER: "Academic master",
  TEACHER: "Teacher",
  ACCOUNTANT: "Accountant",
  PARENT: "Parent",
  STUDENT: "Student",
};
