export const ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN";
export const HEADMASTER = "HEADMASTER";
export const SCHOOL_ADMIN = "SCHOOL_ADMIN";
export const ACADEMIC_MASTER = "ACADEMIC_MASTER";
export const TEACHER = "TEACHER";
export const ACCOUNTANT = "ACCOUNTANT";
export const STAFF = "STAFF";
export const INVIGILATOR = "INVIGILATOR";
export const PARENT = "PARENT";
export const STUDENT = "STUDENT";
export const SUPER_ADMIN = "SUPER_ADMIN";

export const PEOPLE_MANAGE = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER];
export const ACADEMIC_STAFF = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER];
export const STUDENT_DIRECTORY = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, ACCOUNTANT, STAFF];
export const TEACHER_MANAGE = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER];
export const TIMETABLE = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, STAFF, INVIGILATOR];
export const EXAMS = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, INVIGILATOR];
export const FINANCE = [HEADMASTER, SCHOOL_ADMIN, ACCOUNTANT, PARENT];
export const FINANCE_MANAGE = [ACCOUNTANT];
export const ASSIGNMENTS = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, STUDENT, PARENT];
export const REPORTS = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, ACCOUNTANT, TEACHER];
export const MESSAGES = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, ACCOUNTANT, PARENT];
export const NOTICES = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, TEACHER, ACCOUNTANT, STAFF, STUDENT, PARENT];
export const AUDIT = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, ACCOUNTANT];
export const DASHBOARD = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, ACCOUNTANT];
export const SCHOOL_OFFICERS = [HEADMASTER, SCHOOL_ADMIN, ACADEMIC_MASTER, ACCOUNTANT, STAFF, INVIGILATOR];
export const ORG_SCHOOLS = [SUPER_ADMIN, ORGANIZATION_ADMIN];

export function hasRole(role, roles) {
  return Boolean(role && roles.includes(role));
}

export const ROLE_LABELS = {
  SUPER_ADMIN: "Platform admin",
  ORGANIZATION_ADMIN: "Organization admin",
  SCHOOL_ADMIN: "School admin",
  HEADMASTER: "Headmaster",
  ACADEMIC_MASTER: "Academic master",
  TEACHER: "Teacher",
  ACCOUNTANT: "Accountant",
  STAFF: "Staff",
  INVIGILATOR: "Invigilator",
  PARENT: "Parent",
  STUDENT: "Student",
};
